name: FACEIT pipeline

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run ingest
        env:
          FACEIT_API_KEY: ${{ secrets.FACEIT_API_KEY }}
        run: node scripts/ingest.mjs

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run parser
        env:
          FACEIT_API_KEY: ${{ secrets.FACEIT_API_KEY }}
        run: |
          cd parser
          go mod tidy
          go build -o ../parser.bin
          cd ..
          ./parser.bin
          rm -f parser.bin

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/matches.json data/state.json data/highlights.json data/leaderboards.json parser/go.mod parser/go.sum
            git commit -m "chore(pipeline): update data files"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit"
          fi
